name: flutter_go_chat
description: "Messenger client."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.6
  path: ^1.9.1
  rxdart: ^0.27.7
  flutter_resizable_container: ^4.2.0
  window_manager: ^0.5.1
  google_fonts: ^8.1.0
  drift: ^2.34.0
  sqlite3_flutter_libs: ^0.6.0+eol
  sqlite3: ^3.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.34.0
  build_runner: ^2.4.0
  flutter_lints: ^6.0.0

flutter:
  assets:
  - assets/images/rabbit.png
  - assets/themes/theme_orange.json
  
  uses-material-design: true