name: Flutter Build

on:
  push:
    branches:
      - main
      - master
      - client

jobs:
  build-filter:
    runs-on: ubuntu-latest

    outputs:
      should_build: ${{ steps.check.outputs.result }}

    steps:
      - name: Check commit message
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"build"* ]]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi

  android:
    needs: build-filter
    if: needs.build-filter.outputs.should_build == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  windows:
    needs: build-filter
    if: needs.build-filter.outputs.should_build == 'true'

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

  linux:
    needs: build-filter
    if: needs.build-filter.outputs.should_build == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev

      - run: flutter pub get

      - run: flutter build linux --release

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/

  ios:
    needs: build-filter
    if: needs.build-filter.outputs.should_build == 'true'

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter build ios --release --no-codesign

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos/Runner.app